MoviesCore/Controllers/ActorController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MoviesCore.Controllers
{
    public class ActorController : Controller
    {
        ActorManager cm = new ActorManager(new EfActorDal());
        public IActionResult Index()
        {
            var deger = cm.GetList();
            return View(deger);
        }
        [AllowAnonymous]
        public IActionResult Detail(int id)
        {
            var deger = cm.GetById(id);
            return View(deger);
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Add(Actor p)
        {
            if(ModelState.IsValid)
            {
                cm.TAdd(p);
                return RedirectToAction("Index");
            }
            return View();
        }
        public IActionResult Delete(int id)
        {
            var deger = cm.GetById(id);
            cm.TDelete(deger);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Update(int id)
        {
            var deger = cm.GetById(id);
            return View(deger);
        }
        [HttpPost]
        public IActionResult Update(Actor p)
        {
            if(ModelState.IsValid)
            {
                cm.TUpdate(p);
                return RedirectToAction("Index");
            }
            return View();
        }

    }
}

MoviesCore/Controllers/MovieController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;

namespace MoviesCore.Controllers
{
    //[Authorize(Roles ="Admin")]
    public class MovieController : Controller
    {
        Context c = new Context();
        MovieManager mn = new MovieManager(new EfMovieDal());
        CategoryManager cm = new CategoryManager(new EfCategoryDal());
        CinemaManager mg = new CinemaManager(new EfCinemaDal());
        ProducerManager pm = new ProducerManager(new EfProducerDal());
        ActorManager ac = new ActorManager(new EfActorDal());

        [AllowAnonymous]
        public IActionResult Index(int page=1)
        {
            var usermail = User.Identity.Name;
            var userrole = c.ApplicationUsers.Where(x => x.Email == usermail).Select(y => y.UserRole).FirstOrDefault();
            ViewBag.v2 = userrole;
            var deger = mn.GetListCategory().ToPagedList(page,9);
            return View(deger);
        }
        [AllowAnonymous]
        public IActionResult Detail(int id)
        {
            var usermail = User.Identity.Name;
            var userrole = c.ApplicationUsers.Where(x => x.Email == usermail).Select(y => y.UserRole).FirstOrDefault();
            ViewBag.v2 = userrole;
            var deger=mn.GetListCategoryDetail(id);
            return View(deger);

        }
        [HttpGet]
        public IActionResult Add()
        {
            List<SelectListItem> category=(from x in cm.GetList()
                 select new SelectListItem
                {
                     Text=x.CategoryName,
                     Value=x.CategoryId.ToString()
                    
                }).ToList();
            ViewBag.v1 = category;

            List<SelectListItem> cinema = (from x in mg.GetList()

                                           select new SelectListItem
                                           {
                                               Text=x.CinemaName,
                                               Value=x.CinemaId.ToString()

                                           }).ToList();
            ViewBag.v2 = cinema;

            List<SelectListItem> producer = (from x in pm.GetList()

                                             select new SelectListItem
                                             {
                                                 Text=x.ProducerName,
                                                 Value=x.ProducerId.ToString()

                                             }).ToList();

            ViewBag.v3 = producer;

            List<SelectListItem> actor = (from x in ac.GetList()
                                          select new SelectListItem
                                          {

                                              Text=x.ActorName,
                                              Value=x.ActorId.ToString()

                                          }).ToList();
            ViewBag.v4 = actor;

            

            return View();
        }
        [HttpPost]
        public IActionResult Add(Movie p)
        {
            if(ModelState.IsValid)
            {
                p.MovieCreateDate = DateTime.Now;
                mn.TAdd(p);
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet]
        public IActionResult Update(int id)
        {
            List<SelectListItem> category = (from x in cm.GetList()
                                             select new SelectListItem
                                             {
                                                 Text = x.CategoryName,
                                                 Value = x.CategoryId.ToString()

                                             }).ToList();
            ViewBag.v1 = category;

            List<SelectListItem> cinema = (from x in mg.GetList()

                                           select new SelectListItem
                                           {
                                               Text = x.CinemaName,
                                               Value = x.CinemaId.ToString()

                                           }).ToList();
            ViewBag.v2 = cinema;

            List<SelectListItem> producer = (from x in pm.GetList()

                                             select new SelectListItem
                                             {
                                                 Text = x.ProducerName,
                                                 Value = x.ProducerId.ToString()

                                             }).ToList();

            ViewBag.v3 = producer;

            List<SelectListItem> actor = (from x in ac.GetList()
                                          select new SelectListItem
                                          {

                                              Text = x.ActorName,
                                              Value = x.ActorId.ToString()

                                          }).ToList();
            ViewBag.v4 = actor;
            var deger = mn.GetById(id);
            return View(deger);
        }
        [HttpPost]
        public IActionResult Update(Movie p)
        {
            if(ModelState.IsValid)
            {
                p.MovieCreateDate = DateTime.Now;
                mn.TUpdate(p);
                return RedirectToAction("Index");
            }
            return View();
        }
        public IActionResult Delete(int id)
        {
            var deger = mn.GetById(id);
            mn.TDelete(deger);
            return RedirectToAction("Index");
        }
        public PartialViewResult MovieSearch(string p)
        {
            var deger = mn.GetList(p);
            return PartialView(deger);
        }
    }
}

MoviesCore/Views/Movie/Add.cshtml
@model EntityLayer.Concrete.Movie
@{
    ViewData["Title"] = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <form class="form-group" method="post">
            <label><b>Movie Name</b></label>
            @Html.TextBoxFor(x => x.MovieName, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.MovieName, "", new { @class = "text-danger" })
            <br />
            <label><b>Movie Category</b></label>
            @Html.DropDownListFor(x => x.CategoryId, (List<SelectListItem>)ViewBag.v1, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.CategoryId, "", new { @class = "text-danger" })
            <br />
            <label><b>Movie Cinema</b></label>
            @Html.DropDownListFor(x => x.CinemaId, (List<SelectListItem>)ViewBag.v2, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.CinemaId, "", new { @class = "text-danger" })
            <br />
            <label><b>Movie Actor</b></label>
            @Html.DropDownListFor(x => x.ActorId, (List<SelectListItem>)ViewBag.v4, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.ActorId, "", new { @class = "text-danger" })
            <br />
            <label><b>Movie Producer</b></label>
            @Html.DropDownListFor(x => x.ProducerId, (List<SelectListItem>)ViewBag.v3, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.ProducerId, "", new { @class = "text-danger" })
            <br />
            <label><b>Movie Status</b></label>
            @Html.TextBoxFor(x => x.MovieStatus, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.MovieStatus, "", new { @class = "text-danger" })
            <br />
            <label><b>Movie Image</b></label>
            @Html.TextBoxFor(x => x.MovieImageUrl, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.MovieImageUrl, "", new { @class = "text-danger" })
            <br />
            <label><b>Movie Description</b></label>
            @Html.TextAreaFor(x => x.MovieDescription,10,3, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.MovieDescription, "", new { @class = "text-danger" })
            <br />
            <div class="form-group">
                <button class="btn btn-outline-success float-right">Create</button>
                <a class="btn btn-outline-secondary" asp-action="Index">Show all</a>
            </div>

        </form>
    </div>

</div>

MoviesCore/Views/Movie/Detail.cshtml
@using EntityLayer.Concrete
@model List<Movie> 
@{
    ViewData["Title"] = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-8 offset-2">
        @foreach (var x in Model)
        {
        <div class="card md-12">
            <div class="row g-0">
                <div class="col-md-12">
                    <div class="card-header text-white bg-info">
                        <p class="card-text">
                            <h5 class="card-title">
                                @x.MovieName
                            </h5>
                        </p>
                    </div>
                </div>
                <div class="col-md-4">
                    <img src="@x.MovieImageUrl" width="100%" alt="@x.MovieName" />
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        @*<p class="card-text">@x.MovieDescription</p>*@
                        <p class="card-text">
                            <b>Cinema: </b>
                            <a href="/Cinema/Detail/@x.Cinema.CinemaId">
                                @x.Cinema.CinemaName
                            </a>
                        </p>
                        <p class="card-text">
                            <b>Producer: </b>
                            <a href="/Producer/Detail/@x.ProducerId">
                                @x.Producer.ProducerName
                            </a>
                        </p>
                        <p class="card-text"> <b>Category: </b>@x.Category.CategoryName</p>
                        <p class="card-text"> <b>Create Date: </b>@(((DateTime)x.MovieCreateDate).ToString("dd-MMM-yyyy"))</p>
                        <p class="card-text"> <b>Status: </b><span class="badge bg-success text-white">@x.MovieStatus</span></p>
                        <p class="card-text">
                            <b>Actor: </b>
                            <hr />
                            <div class="row">
                                @foreach (var n in Model)
                                {
                                    <div class="column text-center">
                                        <img class="border-info rounded-circle" src="@n.Actor.ActorPhoto" style="max-width: 75px" />
                                        <br />
                                        <a asp-controller="Actor" asp-action="Detail" asp-route-id="@n.ActorId">@n.Actor.ActorName</a>
                                    </div>
                                }
                            </div>
                        </p>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="card-footer">
                        <p class="card-text">
                            <h2>Filmin Konusu</h2>
                            <br/>
                            @x.MovieDescription
                        </p>
                    </div>
                </div> 
                <div class="col-md-12">
                    <div class="card-footer">
                        <p class="card-text">
                            <a class="btn btn-outline-primary float-right" href="/Movie/Index">
                                Back to List
                            </a>
                            @if (User.Identity.IsAuthenticated && ViewBag.v2 == "Admin")
                            { 
                                <a class="btn btn-outline-info" href="/Movie/Update/@x.MovieId">
                                    Update
                                </a>
                            }
                        </p>
                    </div>
                </div>
            </div>
        </div>
        }
    </div>
</div>

MoviesCore/Views/Movie/Index.cshtml
@using EntityLayer.Concrete
@using X.PagedList
@using X.PagedList.Mvc.Core
@model IPagedList<Movie>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
@*<link href="~/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" />*@
<div class="row">
    @foreach (var x in Model)
    {
        <div class="col-md-4 col-xs-6 border-primary mb-3">
            <div class="card mb-3" style="max-width:540px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-danger">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @x.MovieName
                                    @if (User.Identity.IsAuthenticated && ViewBag.v2 == "Admin")
                                    {
                                        <a class="text-white float-right" href="/Movie/Delete/@x.MovieId"><i class="bi bi-pencil-square"></i></a>
                                        
                                    }

                                </h5>

                            </p>

                        </div>

                    </div>
                    <div class="col-md-6">
                        <img src="@x.MovieImageUrl" width="100%" alt="@x.MovieName" />

                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <p class="card-text">@x.MovieDescription.Substring(0, x.MovieDescription.Substring(0, 20).LastIndexOf(" "))...</p>
                            <p class="card-text"><b>Cinema: </b>@x.Cinema.CinemaName</p>
                            <p class="card-text"><b>Category: </b>@x.Category.CategoryName</p>
                            <p class="card-text"><b>Date: </b>@(((DateTime)x.MovieCreateDate).ToString("dd-MMM-yyyy"))</p>
                            <p class="card-text"><b>Status:</b><span class="badge bg-success text-white">@x.MovieStatus</span></p>

                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer">
                            <p class="card-text">
                                <a class="btn btn-outline-primary float-right" href="/Movie/Detail/@x.MovieId">
                                    <i class="bi bi-eye-fill"></i>Show Details
                                </a>
                                
                            </p>
                            @*<p class="card-text">
                                <a class="btn btn-outline-primary" href="/Movie/Detail/@x.MovieId">
                                    <i class="bi bi-eye-fill"></i>Show Details
                                </a>
                                
                            </p>*@

                        </div>
                    </div>
                </div>
            </div>
        </div>

    }
    @if (User.Identity.IsAuthenticated && ViewBag.v2 == "Admin")
    {
        <div style="position: fixed; right: 25px; bottom: 25px;" class="text-white">
            <a href="/Movie/Add" class="btn btn-success">
                <i class="bi bi-plus-circle"></i> Add New
            </a>
        </div>
    }
</div>
  @Html.PagedListPager((IPagedList)Model,page=>Url.Action("Index",new {page}))

MoviesCore/Views/Movie/MovieSearch.cshtml
@using EntityLayer.Concrete
@model List<Movie>  



@foreach(var x in Model)
            {
                <p>@x.MovieName</p>
            }

MoviesCore/Views/Movie/Update.cshtml
@model EntityLayer.Concrete.Movie
@{
    ViewData["Title"] = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <h1>Update</h1>
        @using (Html.BeginForm("Update", "Movie", FormMethod.Post))
        {

            @Html.HiddenFor(x => x.MovieId, new { @class = "form-control" })
            <br />
            <label><b>Movie Name</b></label>
            @Html.TextBoxFor(x => x.MovieName, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.MovieName, "", new { @class = "text-danger" })
            <br />
            <label><b>Movie Category</b></label>
            @Html.DropDownListFor(x => x.CategoryId, (List<SelectListItem>)ViewBag.v1, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.CategoryId, "", new { @class = "text-danger" })
            <br />
            <label><b>Movie Cinema</b></label>
            @Html.DropDownListFor(x => x.CinemaId, (List<SelectListItem>)ViewBag.v2, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.CinemaId, "", new { @class = "text-danger" })
            <br />
            <label><b>Movie Actor</b></label>
            @Html.DropDownListFor(x => x.ActorId, (List<SelectListItem>)ViewBag.v4, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.ActorId, "", new { @class = "text-danger" })
            <br />
            <label><b>Movie Producer</b></label>
            @Html.DropDownListFor(x => x.ProducerId, (List<SelectListItem>)ViewBag.v3, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.ProducerId, "", new { @class = "text-danger" })
            <br />
            <label><b>Movie Status</b></label>
            @Html.TextBoxFor(x => x.MovieStatus, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.MovieStatus, "", new { @class = "text-danger" })
            <br />
            <label><b>Movie Image</b></label>
            @Html.TextBoxFor(x => x.MovieImageUrl, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.MovieImageUrl, "", new { @class = "text-danger" })
            <br />
            <label><b>Movie Description</b></label>
            @Html.TextAreaFor(x => x.MovieDescription, 10, 3, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.MovieDescription, "", new { @class = "text-danger" })
            <br/>
            <div class="form-group">
                <button class="btn btn-outline-warning float-right">Update</button>
                <a class="btn btn-outline-secondary" asp-action="Index">Cancel</a>
            </div>


        }
    </div>
</div>